version: '3.7'
services:
  node:
    build: docker/node
    working_dir: /app
    volumes:
      - .:/app

  http:
    build: docker/http
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - .:/app